### ISSUE TITLE
What's the "parter_short_name"?

### ISSUE THREAD

**Issue by ChaosPKU** [coursera/courseraresearchexports#23]
I had created my data export job request by command like this:
`
courseraresearchexports jobs request tables --course_slug $COURSE_SLUG --purpose "testing data export"
`
Then I downloaded the data and created a docker container. But when I wanted to create a view in the postgres database, I was always requested to provide a argument `parter_short_name`. I even don't know what it is. Anyone can help me?

**Comment by ChaosPKU** [comment]
I have find my institution's name from https://www.coursera.org/api/partners.v1 and try that short name but it didn't work. It's really confusing.

**Comment by cliu587** [comment]
Apologies about the confusing nature of `partner_short_name`. It should be possible to automatically infer this in the future. I'll add an issue for this as a task.

Can you paste the error? A command that worked for me is
`courseraresearchexports db create_view {CONTAINER_NAME} --view_name demographic_survey --partner_short_name coursera`

**Comment by ChaosPKU** [comment]
`Chaos:~ Apple$ courseraresearchexports db create_view ruanjian-gongcheng --view_name demographic_survey --partner_short_name pku
ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/courseraresearchexports/main.py", line 86, in main
    return args.func(args)
  File "/usr/local/lib/python2.7/site-packages/courseraresearchexports/commands/db.py", line 49, in create_view
    args.partner_short_name, d)
  File "/usr/local/lib/python2.7/site-packages/courseraresearchexports/db/db.py", line 82, in create_registered_view
    export_db.create_view(view_name, sql_text_with_partner_short_name)
  File "/usr/local/lib/python2.7/site-packages/courseraresearchexports/models/ExportDb.py", line 69, in create_view
    self.engine.execute(view_statement)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 906, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text
    statement, parameters
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) column a.pku_user_id does not exist
LINE 26:     a.pku_user_id
             ^
 [SQL: "\n        DROP VIEW IF EXISTS demographic_survey;\n        CREATE VIEW demographic_survey AS --demographic_survey\n--This query partially denormalizes the demographics tables to create aggregate\n--information about the users in the present data export.\n--\n--Columns\n--coursera_user_id\n--demographic_survey_submission_dt\n--demographic_survey_gender\n--demographic_survey_age\n--demographic_survey_country_cd_of_birth\n--demographic_survey_us_postal_code\n--demographic_survey_spanish_hispanic_or_latino_descent\n--demographic_survey_race\n--demographic_survey_highest_level_of_schooling\n--demographic_survey_currently_enrolled_in_an_educational_program\n--demographic_survey_level_of_current_educational_program\n--demographic_survey_subject_area_of_degree\n--demographic_survey_current_employment_status\n--demographic_survey_area_of_industry_currently_employed_in\n--demographic_survey_english_proficiency\n--demographic_survey_other_languages_spoken\n\nSELECT\n    a.pku_user_id\n    ,MAX(a.submission_ts::DATE) AS demographic_survey_submission_dt\n    ,MAX(CASE WHEN a.question_id = 11\n        THEN c.choice_desc END) AS demographic_survey_gender\n    ,MAX(CASE WHEN a.question_id = 12\n        THEN DATE_PART('y', CURRENT_DATE) - a.answer_int END) AS demographic_survey_age\n    ,UPPER(LEFT(MAX(CASE WHEN a.question_id = 13\n        THEN c.choice_desc END), 2)) AS demographic_survey_country_cd_of_birth\n    ,MAX(CASE WHEN a.question_id = 15\n        THEN a.answer_int END) AS demographic_survey_us_postal_code\n    ,MAX(CASE WHEN a.question_id = 16\n        THEN c.choice_desc END) AS demographic_survey_spanish_hispanic_or_latino_descent\n    ,RTRIM(STRING_AGG(CASE WHEN a.question_id = 17 THEN c.choice_desc END, ';')) AS demographic_survey_race\n    ,MAX(CASE WHEN a.question_id = 18\n        THEN c.choice_desc END) AS demographic_survey_highest_level_of_schooling\n    ,MAX(CASE WHEN a.question_id = 19\n        THEN c.choice_desc END) AS demographic_survey_currently_enrolled_in_an_educational_program\n    ,MAX(CASE WHEN a.question_id = 20\n        THEN c.choice_desc END) AS demographic_survey_level_of_current_educational_program\n    ,RTRIM(STRING_AGG(CASE WHEN a.question_id = 21\n        THEN c.choice_desc END, ';')) AS demographic_survey_subject_area_of_degree\n    ,MAX(CASE WHEN a.question_id = 22\n        THEN c.choice_desc END) AS demographic_survey_current_employment_status\n    ,MAX(CASE WHEN a.question_id = 23\n        THEN c.choice_desc END) AS demographic_survey_area_of_industry_currently_employed_in\n    ,MAX(CASE WHEN a.question_id = 24\n        THEN c.choice_desc END) AS demographic_survey_english_proficiency\n    ,RTRIM(STRING_AGG(CASE WHEN a.question_id = 25\n        THEN c.choice_desc END, ';')) AS demographic_survey_other_languages_spoken\nFROM demographics_answers a\nJOIN demographics_choices c USING (question_id, choice_id)\nWHERE a.question_id BETWEEN 11 AND 25\n    AND a.question_id = c.question_id\n    AND a.choice_id = c.choice_id\nGROUP BY 1\n;\n        "]`
I can find the column "pku_user_id" in my dataset. And I also try your suggestion "coursera" but I get the error above again.

**Comment by cliu587** [comment]
Did you export with the `demographics` schema? If not, then creating the view will not succeed because it uses the tables exported with the `demographics` domain.

To check, you can connect to the database running in docker (see Using docker, you can connect to the database by running:), and run `select * from demographics_questions;` which will see if this table exists.

If not, try requesting an export with all the schemas (see https://github.com/coursera/courseraresearchexports#request)

**Comment by ChaosPKU** [comment]
I have requested an export with all the schemas at the beginning. And I can see the correct result by typing the command you advised. I think there must be something wrong but I can't find it.

**Comment by tlee-coursera** [comment]
Sorry, this was closed automatically during a pull request. We have resolved this issue in the latest version.  Most likely, you exported with the default setting of `isolated` user_id_hashing, which should no longer be a problem. 

I'll post again when this is released, hopefully before the end of today.

**Comment by tlee-coursera** [comment]
This issue should be resolved in the latest version so I'll close this issue. Please feel free to contact us if you're still having problems creating views. Thanks!
