### ISSUE TITLE
Allow output of `courseraresearchexports jobs clickstream_download_links` to be piped

### ISSUE THREAD

**Issue by cliu587** [coursera/courseraresearchexports#28]
Seems like right now we don't actually print to stdout so redirecting to a file, piping to wget, etc doesn't work.

**Comment by tlee-coursera** [comment]
I believe the logging framework defaults its output stream to stderr, we can change that to stdout.  It might not be ideal for piping to other commands as it'll include the logging level tags (INFO, DEBUG, etc).
