### ISSUE TITLE
DockerException: Error while fetching server API version

### ISSUE THREAD

**Issue by morganpatz** [coursera/courseraresearchexports#33]
Hi, when I run the `courseraresearchexports containers create` in both the specified ways, I am getting the same error:

`ERROR:root:Problem when running command. Sorry!`
```
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\courseraresearchexports\main.py", line 86, in main
    return args.func(args)
  File "c:\python27\lib\site-packages\courseraresearchexports\commands\containers.py", line 31, in create_container
    d = utils.docker_client(args.docker_url, args.timeout)
  File "c:\python27\lib\site-packages\courseraresearchexports\containers\utils.py", line 121, in docker_client
    version='auto')
  File "c:\python27\lib\site-packages\docker\client.py", line 99, in __init__
    self._version = self._retrieve_server_version()
  File "c:\python27\lib\site-packages\docker\client.py", line 124, in _retrieve_server_version
    'Error while fetching server API version: {0}'.format(e)
DockerException: Error while fetching server API version: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
```

Please advise. Thank you.

**Comment by tlee-coursera** [comment]
Could you verify that docker is installed and running using the following commands?
```
which docker
docker version
```

**Comment by morganpatz** [comment]
Thank you. It was a docker issue. It is resolved now.

**Comment by Mandywyy** [comment]
Could you please more detail about how you solve the issue? I came to the same problem here and my docker has been installed and was running. I am using Windows 10 and Docker Toolbox. Thanks.

**Comment by rsshilli** [comment]
@Mandywyy Run `docker ps -a` at the command prompt. If you get back an error, you have a firewall or something in the way of Docker running properly on your machine.

**Comment by AliAlican** [comment]
On windows I had forgotten to start docker :)

**Comment by spinxsunyi** [comment]
@AliAlican just happen to me. Forgot to start docker. nice

**Comment by lamboktulus1379** [comment]
Same here.  👍

**Comment by chrisw889** [comment]
> On windows I had forgotten to start docker :)

I have never hated myself more, but thanks anyway

**Comment by mateuszzeb** [comment]
So stupid mistake, thanks
