### ISSUE TITLE
"Coursera Data Exports Guide" Gitbook link is broken 404 not found

### ISSUE THREAD

**Issue by jeffweilee** [coursera/courseraresearchexports#53]
[Coursera Data Exports Guide](https://coursera.gitbooks.io/data-exports/content/introduction/programmatic_access.html) Gitbook link in the readme is broken (404 not found).
https://coursera.gitbooks.io/data-exports/content/introduction/programmatic_access.html

=============
Readme context:

Up to date documentation of the data provided by Coursera for research purposes is available on gitbooks , [Coursera Data Exports Guide](https://coursera.gitbooks.io/data-exports/content/introduction/programmatic_access.html).

For more information on the available tables/schemas, please refer to the [Coursera Data Exports Guide](https://coursera.gitbooks.io/data-exports/content/introduction/programmatic_access.html)/

**Comment by tlee-coursera** [comment]
Thanks! I'll update the link to [https://coursera.gitbooks.io/data-exports/](https://coursera.gitbooks.io/data-exports/). I will note that you'll need to be invited to Gitbooks in order to view the content.

**Comment by jeffweilee** [comment]
Thanks, looking forward to it!
By the way, I wonder if there is any automated command to fetch a request job ID instead of copying and pasting the ID for download manually ... Maybe there is more detail in the Coursera Data Exports Guide?

**Comment by tlee-coursera** [comment]
@jeffweilee, there's no automated command to pipe the job id after making a request to the download command. Alternatively, you can check out https://github.com/LU-C4i/coursera-scheduled-exports for an example of automating this process.

**Comment by jeffweilee** [comment]
Cool, it would be very helpful, thanks a lot!
