### ISSUE TITLE
Not Authorized

### ISSUE THREAD

**Issue by MoonlightStill** [coursera/courseraresearchexports#55]
When I run the instruction " courseraresearchexports jobs request tables --course_slug machine-learning --purpose "testing data export" ", an error occurs with code "Not Authorized". Before this I have executed "courseraoauth2client config authorize --app manage_research_exports" and checked my authority. How should I solve this issue?

**Comment by tlee-coursera** [comment]
Are you staff/admin for the course you're requesting data for? The "Not authorized" message is typically a result of not having permission to access data for the export scope.

**Comment by MoonlightStill** [comment]
Thanks for your reply. I am not a staff/admin. So are there some open datasets of coursera courses accessible for all users? Because my research topic is about user-modeling and recommendation in online education, more datasets are needed to verify my model and algorithm.

**Comment by tlee-coursera** [comment]
There aren't any open datasets that I know of, sorry. Closing this issue since it's not a problem with the package.
